# Generated by Django 3.2.25 on 2025-07-02 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lms_app', '0003_book_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='client_address',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='book',
            name='client_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='book',
            name='client_phone',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
